
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Contexto
{

using System;
    using System.Collections.Generic;
    
public partial class Proveedores
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Proveedores()
    {

        this.Orden_Compra = new HashSet<Orden_Compra>();

    }


    public int id_proveedor { get; set; }

    public string nombre_prov { get; set; }

    public string saldo { get; set; }

    public Nullable<int> id_articulo { get; set; }



    public virtual Articulos Articulos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Orden_Compra> Orden_Compra { get; set; }

}

}
